name: Reusable Deploy
# allows this workflow to be called in other workflows
on: workflow_call
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output Information
        run: echo "Deploying & Uploading"