name: Reusable Deploy
# allows this workflow to be called in other workflows
#on: workflow_call
on:
  workflow_call:
    # adding inputs or moving params (like a reusable function)
    inputs:
      artifact-name:
        description: The name of the deploying artifact files
        required: false
        default: dist
        type: string
        #resuable retrieve output from jobs
    outputs:
      result:
        description: The result of the the deployment operation
        value: ${{ jobs.deploy.outputs.outcome }}
#    secrets:
#      some-secret:
#        required: false
jobs:
  deploy:
    #resuable retrieve output from steps
    outputs:
      outcome: ${{ steps.set_result_id.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: list files
        run: ls
      - name: Output Information
        run: echo "Deploying & Uploading"
        #resuable set output
      - name: set Result output
        id: set_result_id
#        run: echo "::set-output name=step-result::success"
        run: echo "step-result=success" >> $GITHUB_OUTPUT