name: Reusable Deploy
# allows this workflow to be called in other workflows
#on: workflow_call
on:
  workflow_call:
    # adding inputs or moving params (like a reusable function)
    inputs:
      artifact-name:
        description: The name of the deploying artifact files
        required: false
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: list files
        run: ls
      - name: Output Information
        run: echo "Deploying & Uploading"